name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: docker://docker:17.09.0-ce-git
    - uses: actions/checkout@v1
    - run: docker build --no-cache -t lowieh/ddns-name-com:latest .
    - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASS: ${{secrets.DOCKER_PASS}}
    - run: docker push lowieh/ddns-name-com:latest
